---------------------------------
#### Single layer perceptron - using sklearn
-----------------------

- `sklearn.linear_model.Perceptron`

The Perceptron is another simple classification algorithm suitable for large scale learning. By default:

- It does not require a learning rate.
- It is not regularized (penalized).
- It updates its model only on mistakes.

The last characteristic implies that the Perceptron is slightly `faster `

#### Parameters
- `penalty` {`l2`, `l1`, `elasticnet`}, `default=None` - The penalty (aka `regularization` term) to be used.

- `alpha` float, default=0.0001 - Constant that multiplies the regularization term `if regularization` is used.

- `l1_ratio` float, default=0.15 - The `Elastic Net` mixing parameter, with 0 <= l1_ratio <= 1. 
        - l1_ratio=0 corresponds to L2 penalty, 
        - l1_ratio=1 to L1. 
    - Only used if penalty='elasticnet'.

- `fit_intercept` bool, `default=True` - Whether the intercept should be estimated or not. `If False`, the data is assumed to be already centered.

- `max_iter` int, default=1000 - The maximum number of passes over the training data (aka epochs). 

- `tol` float, default=1e-3 - The `stopping criterion`. 
    - If it is not `None`, the iterations will stop when (`loss > previous_loss - tol`).

- `shuffle` bool, default=True - Whether or not the training data should be shuffled after each epoch.

- `verbose` int, default=0 - The verbosity level

- `eta` - double, `default=1` - Constant by which the updates are multiplied.

- `early_stopping` bool, `default=False` - Whether to use early stopping to terminate training when validation. score is not improving. 
    - If set to True, it will automatically set aside a `stratified fraction` of training data as validation and terminate training when validation score is not improving by at least tol for `n_iter_no_change` consecutive epochs.

- `validation_fraction` float, default=0.1 - The proportion of training data to set aside as validation set for `early stopping`. Must be between 0 and 1. 
    - `Only used if early_stopping is True`.

- `n_iter_no_change` int, default=5 - Number of iterations with no improvement to wait before early stopping.

- `class_weight` dict, {class_label: weight} or “balanced”, `default=None` - Preset for the class_weight fit parameter. Weights associated with classes. 
    - If not given, all classes are supposed to have weight one.
    - The “balanced” mode uses the values of y to automatically adjust weights inversely proportional to class frequencies in the input data as n_samples / (n_classes * np.bincount(y))

    - `warm_start` - bool, `default=False` - When set to True, reuse the solution of the previous call to fit as initialization, otherwise, just erase the previous solution. 

In [1]:
# Load required libraries
from sklearn import datasets
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import Perceptron

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd

In [2]:
# Load The Iris Data
iris = datasets.load_iris()

# Create our X and y data
X = iris.data
y = iris.target

In [3]:
pd.DataFrame(X, columns=iris.feature_names)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [6]:
# Split the data into 70% training data and 30% test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [7]:
X_train.shape, X_test.shape

((105, 4), (45, 4))

In [8]:
# Train the scaler, which standarizes all the features to have mean=0 and unit variance
sc = StandardScaler()

sc.fit(X_train)

StandardScaler()

In [9]:
sc.mean_,sc.var_

(array([5.82571429, 3.0647619 , 3.66571429, 1.17142857]),
 array([0.73543401, 0.20018685, 3.21615782, 0.58756463]))

In [10]:
# Apply the scaler to the X training data
X_train_std = sc.transform(X_train)

# Apply the SAME scaler to the X test data
X_test_std = sc.transform(X_test)

#### Create a perceptron object with the parameters: 
- 40 iterations (epochs) over the data, 
- and a learning rate of 0.1

-`Fit` linear model with `Stochastic Gradient Descent`.

In [11]:
ppn = Perceptron(max_iter     = 90, 
                 eta0         = .001,  # learning rate
                 tol          = 0.1,   # default, 0.001
                 random_state = 0)

# Train the perceptron
ppn.fit(X_train_std, y_train)

Perceptron(eta0=0.001, max_iter=90, tol=0.1)

In [12]:
print('Classes   : \n', ppn.classes_)
print('Weights   : \n', ppn.coef_)
print('Intercept : \n', ppn.intercept_)
print('nbr Iter  : \n', ppn.n_iter_)

Classes   : 
 [0 1 2]
Weights   : 
 [[-0.0012527   0.00193276 -0.00197076 -0.00160278]
 [-0.00078627 -0.00298429  0.00438601 -0.00186369]
 [ 0.00041313 -0.00047255  0.00289639  0.00551653]]
Intercept : 
 [-0.001 -0.001 -0.006]
nbr Iter  : 
 6


In [13]:
# Apply the trained perceptron on the X data to make predicts for the y test data
y_pred = ppn.predict(X_test_std)

# View the accuracy of the model, which is: 1 - (observations predicted wrong / total observations)
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

Accuracy: 0.87


In [14]:
y_pred

array([1, 2, 0, 2, 1, 0, 0, 2, 1, 0, 0, 2, 1, 0, 1, 2, 1, 2, 1, 2, 2, 1,
       2, 0, 2, 1, 1, 1, 0, 0, 0, 1, 0, 2, 2, 1, 1, 2, 2, 1, 0, 0, 1, 1,
       1])

#### another configuration

In [15]:
ppn = Perceptron(max_iter = 2500, 
                 tol      = 0.001, 
                 eta0     = .01, 
                 random_state=0)

# Train the perceptron
ppn.fit(X_train_std, y_train)

# Apply the trained perceptron on the X data to make predicts for the y test data
y_pred = ppn.predict(X_test_std)

# View the accuracy of the model, which is: 1 - (observations predicted wrong / total observations)
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

Accuracy: 0.87


In [16]:
print('Classes   : \n', ppn.classes_)
print('Weights   : \n', ppn.coef_)
print('Intercept : \n', ppn.intercept_)
print('Iterations: \n', ppn.n_iter_)

Classes   : 
 [0 1 2]
Weights   : 
 [[-0.01252703  0.01932764 -0.01970757 -0.01602775]
 [-0.00786271 -0.02984289  0.04386009 -0.01863692]
 [ 0.00413125 -0.00472548  0.02896391  0.05516528]]
Intercept : 
 [-0.01 -0.01 -0.06]
Iterations: 
 6


#### use early stopping

In [20]:
ppn = Perceptron(max_iter    = 2500, 
                 tol         = 0.001, 
                 eta0        = .001, 
                 random_state= 0,
                 early_stopping     = True,
                 validation_fraction= 0.1,
                 n_iter_no_change   = 5,
                 verbose=2
                )

# Train the perceptron
ppn.fit(X_train_std, y_train)

# Apply the trained perceptron on the X data to make predicts for the y test data
y_pred = ppn.predict(X_test_std)

# View the accuracy of the model, which is: 1 - (observations predicted wrong / total observations)
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

-- Epoch 1
Norm: 0.00, NNZs: 4, Bias: 0.000000, T: 94, Avg. loss: 0.000001
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 0.00, NNZs: 4, Bias: 0.000000, T: 188, Avg. loss: 0.000000
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 0.00, NNZs: 4, Bias: 0.000000, T: 282, Avg. loss: 0.000000
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 0.00, NNZs: 4, Bias: 0.000000, T: 376, Avg. loss: 0.000000
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 0.00, NNZs: 4, Bias: 0.000000, T: 470, Avg. loss: 0.000000
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 0.00, NNZs: 4, Bias: 0.000000, T: 564, Avg. loss: 0.000000
Total training time: 0.00 seconds.
Convergence after 6 epochs took 0.00 seconds
-- Epoch 1
Norm: 0.00, NNZs: 4, Bias: -0.003000, T: 94, Avg. loss: 0.000600
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 0.00, NNZs: 4, Bias: -0.004000, T: 188, Avg. loss: 0.000612
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 0.01, NNZs: 4, Bias: -0.001000, T: 282, Avg. loss:

In [18]:
ppn.max_iter, ppn.n_iter_

(2500, 8)

In [19]:
ppn.coef_

array([[-5.83039728e-04,  1.78801936e-03, -1.44978857e-03,
        -1.43504283e-03],
       [-9.62848465e-04, -1.26225652e-03,  3.75511172e-03,
        -3.74602091e-03],
       [-4.63100127e-04, -9.15295623e-05,  2.20973269e-03,
         3.76465783e-03]])